version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: leads
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"

traefik:
  image: traefik:v2.13
  command:
    - --api.insecure=true
    - --providers.docker=true
    - --entrypoints.web.address=:80
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

nginx:
  image: nginx:stable
  ports:
    - "8081:80"
  volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
